version: "3.9"

services:
  backend:
    image: tanishqtyagi/python:Backend_Blog_1.0 #my docker image                 # Use a prebuilt local image or push to Docker Hub
    container_name: blog_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:5.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_USERNAME}", "--password", "${MONGO_PASSWORD}", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


